#!/usr/bin/env node
/**
 * Emits dotnet/Djengo.Shared/Permissions.g.cs from src/permissions.ts.
 *
 * Runs as part of `npm run build`, after tsc has produced dist/. The .NET
 * services don't consume npm packages, so `npm run sync:dotnet` copies the
 * generated file into each service afterwards.
 *
 * This is also where the catalog is validated. A slug that exists in the enum
 * but has no catalog row would seed into no group and be ungrantable from the
 * UI; a group referencing an unknown slug would silently drop. Both are caught
 * here rather than at seed time.
 */
const fs = require("fs");
const path = require("path");

const PKG_ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(PKG_ROOT, "dotnet", "Djengo.Shared");
const OUT_FILE = path.join(OUT_DIR, "Permissions.g.cs");

/** Postgres column is VarChar(50). */
const MAX_SLUG_LENGTH = 50;

const {
  PermissionName,
  ALL_PERMISSIONS,
  PERMISSION_GROUPS,
} = require(path.join(PKG_ROOT, "dist", "src", "permissions.js"));

function fail(messages) {
  console.error("\nPermission catalog is inconsistent:\n");
  for (const m of messages) console.error(`  - ${m}`);
  console.error("");
  process.exit(1);
}

function validate() {
  const errors = [];
  const enumSlugs = new Set(Object.values(PermissionName));
  const rowSlugs = new Set(ALL_PERMISSIONS.map((p) => p.name));

  for (const slug of enumSlugs) {
    if (!rowSlugs.has(slug)) {
      errors.push(
        `PermissionName carries "${slug}" but ALL_PERMISSIONS has no row for it — it would never be seeded.`,
      );
    }
  }
  for (const slug of rowSlugs) {
    if (!enumSlugs.has(slug)) {
      errors.push(`ALL_PERMISSIONS defines "${slug}" with no PermissionName member.`);
    }
  }

  const seen = new Set();
  for (const p of ALL_PERMISSIONS) {
    if (seen.has(p.name)) errors.push(`"${p.name}" is defined twice in ALL_PERMISSIONS.`);
    seen.add(p.name);
    if (p.name.length > MAX_SLUG_LENGTH) {
      errors.push(
        `"${p.name}" is ${p.name.length} chars; permission_name is VarChar(${MAX_SLUG_LENGTH}).`,
      );
    }
    if (!/^[a-z][a-z0-9_]*$/.test(p.name)) {
      errors.push(`"${p.name}" is not a lower_snake_case slug.`);
    }
  }

  for (const group of PERMISSION_GROUPS) {
    for (const slug of group.permissions) {
      if (!rowSlugs.has(slug)) {
        errors.push(`Group "${group.group_name}" references unknown permission "${slug}".`);
      }
    }
  }

  // A permission outside every group can never be granted from the role editor.
  const grouped = new Set(PERMISSION_GROUPS.flatMap((g) => g.permissions));
  for (const slug of rowSlugs) {
    if (!grouped.has(slug)) {
      errors.push(`"${slug}" belongs to no group, so no role can ever be granted it.`);
    }
  }

  if (errors.length) fail(errors);
}

/** manage_organization -> ManageOrganization */
function pascalCase(slug) {
  return slug
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function escapeXml(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function render() {
  const lines = [];
  const push = (line = "") => lines.push(line);

  push("// <auto-generated>");
  push("//     Generated from backend/djengo-proto-helpers/src/permissions.ts.");
  push("//");
  push("//     Do not edit this file. Change the TypeScript catalog, run");
  push("//     `npm run build` in djengo-proto-helpers, then `npm run sync:dotnet`");
  push("//     to refresh every service, and commit the result.");
  push("// </auto-generated>");
  push();
  push("using System;");
  push("using System.Collections.Generic;");
  push();
  push("namespace Djengo.Shared;");
  push();
  push("/// <summary>");
  push("/// Organization permission slugs, matching the rows organization-service seeds");
  push("/// into its Permission table. A slug that is not in that table resolves to zero");
  push("/// recipients or a denied check, silently — so prefer these constants over");
  push("/// string literals anywhere a permission name crosses a service boundary.");
  push("/// </summary>");
  push("public static class Permissions");
  push("{");

  let previousCategory = null;
  for (const permission of ALL_PERMISSIONS) {
    if (permission.category !== previousCategory) {
      if (previousCategory !== null) push();
      push(`    // ${permission.category}`);
      previousCategory = permission.category;
    }
    push(`    /// <summary>${escapeXml(permission.description)}</summary>`);
    push(`    public const string ${pascalCase(permission.name)} = "${permission.name}";`);
  }

  push();
  push("    /// <summary>Every slug, in catalog order.</summary>");
  push("    public static readonly IReadOnlyList<string> All = new[]");
  push("    {");
  for (const permission of ALL_PERMISSIONS) {
    push(`        ${pascalCase(permission.name)},`);
  }
  push("    };");
  push();
  push("    private static readonly HashSet<string> Known = new(All, StringComparer.Ordinal);");
  push();
  push("    /// <summary>True when the platform recognises <paramref name=\"name\"/> as a permission.</summary>");
  push("    public static bool IsKnown(string name) => Known.Contains(name);");
  push("}");
  push();

  return lines.join("\n");
}

validate();
fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT_FILE, render(), "utf8");
console.log(
  `Generated ${path.relative(PKG_ROOT, OUT_FILE)} (${ALL_PERMISSIONS.length} permissions, ${PERMISSION_GROUPS.length} groups)`,
);
