// <auto-generated>
//     Generated from backend/djengo-proto-helpers/src/permissions.ts.
//
//     Do not edit this file. Change the TypeScript catalog, run
//     `npm run build` in djengo-proto-helpers, then `npm run sync:dotnet`
//     to refresh every service, and commit the result.
// </auto-generated>

using System;
using System.Collections.Generic;

namespace Djengo.Shared;

/// <summary>
/// Organization permission slugs, matching the rows organization-service seeds
/// into its Permission table. A slug that is not in that table resolves to zero
/// recipients or a denied check, silently — so prefer these constants over
/// string literals anywhere a permission name crosses a service boundary.
/// </summary>
public static class Permissions
{
    // BUSINESS_USER
    /// <summary>Manage organization profile and settings</summary>
    public const string ManageOrganization = "manage_organization";
    /// <summary>View settings</summary>
    public const string ViewSettings = "view_settings";
    /// <summary>Change settings</summary>
    public const string ManageSettings = "manage_settings";
    /// <summary>View companies in the organization</summary>
    public const string ViewCompanies = "view_companies";
    /// <summary>Create and update companies</summary>
    public const string ManageCompanies = "manage_companies";
    /// <summary>View branches</summary>
    public const string ViewBranches = "view_branches";
    /// <summary>Create and update branches</summary>
    public const string ManageBranches = "manage_branches";
    /// <summary>Restrict which branches a role can reach</summary>
    public const string RestrictBranchAccess = "restrict_branch_access";
    /// <summary>View departments and designations</summary>
    public const string ViewDepartments = "view_departments";
    /// <summary>Create and update departments and designations</summary>
    public const string ManageDepartments = "manage_departments";
    /// <summary>View roles and role levels</summary>
    public const string ViewRoles = "view_roles";
    /// <summary>Create roles and assign permissions</summary>
    public const string ManageRoles = "manage_roles";
    /// <summary>View partner companies</summary>
    public const string ViewPartners = "view_partners";
    /// <summary>Onboard and manage partner companies</summary>
    public const string ManagePartners = "manage_partners";
    /// <summary>View staff records across the organization</summary>
    public const string ViewStaff = "view_staff";
    /// <summary>Onboard, update and offboard staff</summary>
    public const string ManageStaff = "manage_staff";
    /// <summary>Send and revoke staff invitations</summary>
    public const string ManageInvitations = "manage_invitations";
    /// <summary>View audit logs</summary>
    public const string ViewAudit = "view_audit";
    /// <summary>Manage audit and compliance settings</summary>
    public const string ManageAudit = "manage_audit";

    // DEPARTMENT
    /// <summary>Open kitchen pages</summary>
    public const string AccessKitchen = "access_kitchen";
    /// <summary>Manage kitchen operations and menu</summary>
    public const string ManageKitchen = "manage_kitchen";
    /// <summary>Open reception pages</summary>
    public const string AccessReception = "access_reception";
    /// <summary>Manage reception operations</summary>
    public const string ManageReception = "manage_reception";
    /// <summary>Open hotel pages</summary>
    public const string AccessHotel = "access_hotel";
    /// <summary>Manage hotel operations</summary>
    public const string ManageHotel = "manage_hotel";
    /// <summary>Open restaurant pages</summary>
    public const string AccessRestaurant = "access_restaurant";
    /// <summary>Manage restaurant operations</summary>
    public const string ManageRestaurant = "manage_restaurant";

    // STAFF
    /// <summary>View the dashboard</summary>
    public const string ViewDashboard = "view_dashboard";
    /// <summary>View own profile</summary>
    public const string ViewProfile = "view_profile";
    /// <summary>Edit own profile</summary>
    public const string ManageProfile = "manage_profile";
    /// <summary>Open branch pages</summary>
    public const string AccessBranch = "access_branch";
    /// <summary>Manage branch settings</summary>
    public const string ManageBranch = "manage_branch";
    /// <summary>Work across every branch in the company</summary>
    public const string ViewAllBranches = "view_all_branches";
    /// <summary>View staff at other branches</summary>
    public const string ViewBranchStaff = "view_branch_staff";
    /// <summary>View leave at other branches</summary>
    public const string ViewBranchLeave = "view_branch_leave";
    /// <summary>View approvals at other branches</summary>
    public const string ViewBranchApprovals = "view_branch_approvals";
    /// <summary>View payroll and financials at other branches</summary>
    public const string ViewBranchFinancials = "view_branch_financials";
    /// <summary>View shifts at other branches</summary>
    public const string ViewBranchShifts = "view_branch_shifts";
    /// <summary>View tasks at other branches</summary>
    public const string ViewBranchTasks = "view_branch_tasks";
    /// <summary>View reception at other branches</summary>
    public const string ViewBranchReception = "view_branch_reception";
    /// <summary>View facility at other branches</summary>
    public const string ViewBranchFacility = "view_branch_facility";
    /// <summary>View facility layout and occupancy</summary>
    public const string AccessFacility = "access_facility";
    /// <summary>Manage facility layout and occupancy</summary>
    public const string ManageFacility = "manage_facility";
    /// <summary>View operational data</summary>
    public const string ViewOperations = "view_operations";
    /// <summary>Manage operations</summary>
    public const string ManageOperations = "manage_operations";
    /// <summary>View assigned tasks</summary>
    public const string ViewTasks = "view_tasks";
    /// <summary>Create and assign tasks</summary>
    public const string ManageTasks = "manage_tasks";
    /// <summary>View inventory</summary>
    public const string ViewInventory = "view_inventory";
    /// <summary>Adjust inventory</summary>
    public const string ManageInventory = "manage_inventory";
    /// <summary>View assets</summary>
    public const string ViewAssets = "view_assets";
    /// <summary>Manage assets</summary>
    public const string ManageAssets = "manage_assets";
    /// <summary>View bookings and reservations</summary>
    public const string ViewReservations = "view_reservations";
    /// <summary>Create, edit and check in bookings</summary>
    public const string ManageReservations = "manage_reservations";
    /// <summary>Approve or decline booking requests</summary>
    public const string ApproveReservations = "approve_reservations";
    /// <summary>View guest profiles</summary>
    public const string ViewGuests = "view_guests";
    /// <summary>Create and edit guest profiles</summary>
    public const string ManageGuests = "manage_guests";
    /// <summary>View work schedule</summary>
    public const string ViewSchedule = "view_schedule";
    /// <summary>Create and edit schedules</summary>
    public const string ManageSchedule = "manage_schedule";
    /// <summary>View shifts</summary>
    public const string ViewShifts = "view_shifts";
    /// <summary>Create and assign shifts</summary>
    public const string ManageShifts = "manage_shifts";
    /// <summary>View time tracking records</summary>
    public const string ViewTime = "view_time";
    /// <summary>Manage time and attendance records</summary>
    public const string ManageTime = "manage_time";
    /// <summary>View attendance</summary>
    public const string ViewAttendance = "view_attendance";
    /// <summary>Record and correct attendance</summary>
    public const string ManageAttendance = "manage_attendance";
    /// <summary>View leave requests and balances</summary>
    public const string ViewLeave = "view_leave";
    /// <summary>Submit and manage leave requests</summary>
    public const string ManageLeave = "manage_leave";
    /// <summary>Approve or decline leave requests</summary>
    public const string ApproveLeave = "approve_leave";
    /// <summary>View the company calendar</summary>
    public const string ViewCalendarEvents = "view_calendar_events";
    /// <summary>Create and edit calendar events</summary>
    public const string ManageCalendarEvents = "manage_calendar_events";
    /// <summary>View approval requests</summary>
    public const string ViewApprovals = "view_approvals";
    /// <summary>Act on approval requests routed to the role</summary>
    public const string ManageApprovals = "manage_approvals";
    /// <summary>Configure approval chains and steps</summary>
    public const string ManageApprovalChains = "manage_approval_chains";
    /// <summary>View messages and announcements</summary>
    public const string ViewCommunication = "view_communication";
    /// <summary>Send and manage communications</summary>
    public const string ManageCommunication = "manage_communication";
    /// <summary>View complaints and support tickets</summary>
    public const string ViewComplaints = "view_complaints";
    /// <summary>Respond to and resolve complaints</summary>
    public const string ManageComplaints = "manage_complaints";
    /// <summary>View other staff profiles</summary>
    public const string ViewStaffProfiles = "view_staff_profiles";
    /// <summary>Edit other staff profiles</summary>
    public const string ManageStaffProfiles = "manage_staff_profiles";
    /// <summary>View contracts, documents and performance records</summary>
    public const string ViewHrRecords = "view_hr_records";
    /// <summary>Manage contracts, documents and performance records</summary>
    public const string ManageHrRecords = "manage_hr_records";
    /// <summary>View financial summaries</summary>
    public const string ViewFinances = "view_finances";
    /// <summary>Manage financial settings</summary>
    public const string ManageFinances = "manage_finances";
    /// <summary>View invoices and remittances</summary>
    public const string ViewInvoices = "view_invoices";
    /// <summary>Issue and update invoices</summary>
    public const string ManageInvoices = "manage_invoices";
    /// <summary>Configure billing policies</summary>
    public const string ManageBillingPolicy = "manage_billing_policy";
    /// <summary>View vendors, requisitions and purchase orders</summary>
    public const string ViewProcurement = "view_procurement";
    /// <summary>Raise and manage procurement documents</summary>
    public const string ManageProcurement = "manage_procurement";
    /// <summary>Approve purchase requests and orders</summary>
    public const string ApproveProcurement = "approve_procurement";
    /// <summary>View payroll records</summary>
    public const string ViewPayrolls = "view_payrolls";
    /// <summary>Manage payroll entries</summary>
    public const string ManagePayrolls = "manage_payrolls";
    /// <summary>Approve payroll runs</summary>
    public const string ApprovePayrolls = "approve_payrolls";
    /// <summary>Release payroll for payment</summary>
    public const string SendPayroll = "send_payroll";
    /// <summary>View payroll reports</summary>
    public const string ViewPayrollReports = "view_payroll_reports";
    /// <summary>Configure payroll schedules</summary>
    public const string ManagePayrollSchedules = "manage_payroll_schedules";
    /// <summary>View monthly budgets</summary>
    public const string ViewMonthlyBudgets = "view_monthly_budgets";
    /// <summary>Create and edit monthly budgets</summary>
    public const string ManageMonthlyBudgets = "manage_monthly_budgets";
    /// <summary>Approve monthly budgets</summary>
    public const string ApproveMonthlyBudgets = "approve_monthly_budgets";
    /// <summary>View the branch budget</summary>
    public const string ViewBranchBudget = "view_branch_budget";
    /// <summary>View branch fund allocations</summary>
    public const string ViewBranchAllocations = "view_branch_allocations";
    /// <summary>Manage branch fund allocations</summary>
    public const string ManageBranchAllocations = "manage_branch_allocations";
    /// <summary>Approve branch fund allocations</summary>
    public const string ApproveBranchAllocations = "approve_branch_allocations";
    /// <summary>View fund allocations</summary>
    public const string ViewAllocations = "view_allocations";
    /// <summary>Manage fund allocations</summary>
    public const string ManageAllocations = "manage_allocations";
    /// <summary>Submit fund requests</summary>
    public const string RequestFunds = "request_funds";
    /// <summary>View fund requests</summary>
    public const string ViewFundRequests = "view_fund_requests";
    /// <summary>Approve fund requests</summary>
    public const string ApproveFundRequests = "approve_fund_requests";
    /// <summary>Submit extra fund requests</summary>
    public const string RequestExtraFunds = "request_extra_funds";
    /// <summary>View extra fund requests</summary>
    public const string ViewExtraFundRequests = "view_extra_fund_requests";
    /// <summary>Approve extra fund requests</summary>
    public const string ApproveExtraFundRequests = "approve_extra_fund_requests";
    /// <summary>View disbursements</summary>
    public const string ViewDisbursements = "view_disbursements";
    /// <summary>Manage disbursements</summary>
    public const string ManageDisbursements = "manage_disbursements";
    /// <summary>Approve disbursements</summary>
    public const string ApproveDisbursements = "approve_disbursements";

    /// <summary>Every slug, in catalog order.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        ManageOrganization,
        ViewSettings,
        ManageSettings,
        ViewCompanies,
        ManageCompanies,
        ViewBranches,
        ManageBranches,
        RestrictBranchAccess,
        ViewDepartments,
        ManageDepartments,
        ViewRoles,
        ManageRoles,
        ViewPartners,
        ManagePartners,
        ViewStaff,
        ManageStaff,
        ManageInvitations,
        ViewAudit,
        ManageAudit,
        AccessKitchen,
        ManageKitchen,
        AccessReception,
        ManageReception,
        AccessHotel,
        ManageHotel,
        AccessRestaurant,
        ManageRestaurant,
        ViewDashboard,
        ViewProfile,
        ManageProfile,
        AccessBranch,
        ManageBranch,
        ViewAllBranches,
        ViewBranchStaff,
        ViewBranchLeave,
        ViewBranchApprovals,
        ViewBranchFinancials,
        ViewBranchShifts,
        ViewBranchTasks,
        ViewBranchReception,
        ViewBranchFacility,
        AccessFacility,
        ManageFacility,
        ViewOperations,
        ManageOperations,
        ViewTasks,
        ManageTasks,
        ViewInventory,
        ManageInventory,
        ViewAssets,
        ManageAssets,
        ViewReservations,
        ManageReservations,
        ApproveReservations,
        ViewGuests,
        ManageGuests,
        ViewSchedule,
        ManageSchedule,
        ViewShifts,
        ManageShifts,
        ViewTime,
        ManageTime,
        ViewAttendance,
        ManageAttendance,
        ViewLeave,
        ManageLeave,
        ApproveLeave,
        ViewCalendarEvents,
        ManageCalendarEvents,
        ViewApprovals,
        ManageApprovals,
        ManageApprovalChains,
        ViewCommunication,
        ManageCommunication,
        ViewComplaints,
        ManageComplaints,
        ViewStaffProfiles,
        ManageStaffProfiles,
        ViewHrRecords,
        ManageHrRecords,
        ViewFinances,
        ManageFinances,
        ViewInvoices,
        ManageInvoices,
        ManageBillingPolicy,
        ViewProcurement,
        ManageProcurement,
        ApproveProcurement,
        ViewPayrolls,
        ManagePayrolls,
        ApprovePayrolls,
        SendPayroll,
        ViewPayrollReports,
        ManagePayrollSchedules,
        ViewMonthlyBudgets,
        ManageMonthlyBudgets,
        ApproveMonthlyBudgets,
        ViewBranchBudget,
        ViewBranchAllocations,
        ManageBranchAllocations,
        ApproveBranchAllocations,
        ViewAllocations,
        ManageAllocations,
        RequestFunds,
        ViewFundRequests,
        ApproveFundRequests,
        RequestExtraFunds,
        ViewExtraFundRequests,
        ApproveExtraFundRequests,
        ViewDisbursements,
        ManageDisbursements,
        ApproveDisbursements,
    };

    private static readonly HashSet<string> Known = new(All, StringComparer.Ordinal);

    /// <summary>True when the platform recognises <paramref name="name"/> as a permission.</summary>
    public static bool IsKnown(string name) => Known.Contains(name);
}
