// <auto-generated>
//     Generated from backend/djengo-proto-helpers/src/permissions.ts.
//
//     Do not edit this file. Change the TypeScript catalog, run
//     `npm run build` in djengo-proto-helpers, then `npm run sync:dotnet`
//     to refresh every service, and commit the result.
// </auto-generated>

using System;
using System.Collections.Generic;

namespace Djengo.Shared;

/// <summary>
/// Organization permission slugs, matching the rows organization-service seeds
/// into its Permission table. A slug that is not in that table resolves to zero
/// recipients or a denied check, silently — so prefer these constants over
/// string literals anywhere a permission name crosses a service boundary.
/// </summary>
public static class Permissions
{
    // BUSINESS_USER
    /// <summary>View company details</summary>
    public const string ViewCompanyDetails = "view_company_details";
    /// <summary>Manage company details</summary>
    public const string ManageCompanyDetails = "manage_company_details";
    /// <summary>View plans and billing</summary>
    public const string ViewCompanyPlansBillings = "view_company_plans_billings";
    /// <summary>Manage plans and billing</summary>
    public const string ManageCompanyPlansBillings = "manage_company_plans_billings";
    /// <summary>View all branches</summary>
    public const string ViewAllBranches = "view_all_branches";
    /// <summary>Manage all branches</summary>
    public const string ManageAllBranches = "manage_all_branches";
    /// <summary>View departments</summary>
    public const string ViewDepartments = "view_departments";
    /// <summary>Manage departments</summary>
    public const string ManageDepartments = "manage_departments";
    /// <summary>View roles</summary>
    public const string ViewRoles = "view_roles";
    /// <summary>Manage roles</summary>
    public const string ManageRoles = "manage_roles";
    /// <summary>View staff</summary>
    public const string ViewBranchStaff = "view_branch_staff";
    /// <summary>Manage staff</summary>
    public const string ManageBranchStaff = "manage_branch_staff";
    /// <summary>View invitations</summary>
    public const string ViewInvitations = "view_invitations";
    /// <summary>Manage invitations</summary>
    public const string ManageInvitations = "manage_invitations";
    /// <summary>View company audit logs</summary>
    public const string ViewCompanyAuditLogs = "view_company_audit_logs";
    /// <summary>View compliance</summary>
    public const string ViewCompliance = "view_compliance";
    /// <summary>Manage compliance</summary>
    public const string ManageCompliance = "manage_compliance";

    // DEPARTMENT
    /// <summary>View kitchen analytics</summary>
    public const string ViewKitchenAnalytics = "view_kitchen_analytics";
    /// <summary>View kitchen menu</summary>
    public const string ViewKitchenMenu = "view_kitchen_menu";
    /// <summary>Manage kitchen menu</summary>
    public const string ManageKitchenMenu = "manage_kitchen_menu";
    /// <summary>View kitchen board</summary>
    public const string ViewKitchenBoard = "view_kitchen_board";
    /// <summary>Manage kitchen board</summary>
    public const string ManageKitchenBoard = "manage_kitchen_board";
    /// <summary>View kitchen orders</summary>
    public const string ViewKitchenOrders = "view_kitchen_orders";
    /// <summary>Manage kitchen orders</summary>
    public const string ManageKitchenOrders = "manage_kitchen_orders";
    /// <summary>View reception</summary>
    public const string ViewReception = "view_reception";
    /// <summary>View reception analytics</summary>
    public const string ViewReceptionAnalytics = "view_reception_analytics";

    // STAFF
    /// <summary>View approval chain</summary>
    public const string ViewApprovalChain = "view_approval_chain";
    /// <summary>Manage approval chain</summary>
    public const string ManageApprovalChain = "manage_approval_chain";
    /// <summary>View booking requests</summary>
    public const string ViewBookingRequests = "view_booking_requests";
    /// <summary>Manage bookings</summary>
    public const string ManageBooking = "manage_booking";
    /// <summary>View refund requests</summary>
    public const string ViewRefundRequests = "view_refund_requests";
    /// <summary>Manage refund requests</summary>
    public const string ManageRefundRequests = "manage_refund_requests";
    /// <summary>View guests</summary>
    public const string ViewGuests = "view_guests";
    /// <summary>Manage guests</summary>
    public const string ManageGuests = "manage_guests";
    /// <summary>View staff attendance</summary>
    public const string ViewStaffAttendance = "view_staff_attendance";
    /// <summary>View company contracts</summary>
    public const string ViewCompanyContracts = "view_company_contracts";
    /// <summary>Manage company contracts</summary>
    public const string ManageCompanyContracts = "manage_company_contracts";
    /// <summary>View staff performance</summary>
    public const string ViewStaffPerformance = "view_staff_performance";
    /// <summary>Manage staff performance</summary>
    public const string ManageStaffPerformance = "manage_staff_performance";
    /// <summary>View staff training</summary>
    public const string ViewStaffTraining = "view_staff_training";
    /// <summary>Manage staff training</summary>
    public const string ManageStaffTraining = "manage_staff_training";
    /// <summary>View disciplinary records</summary>
    public const string ViewDisciplinaryRecords = "view_disciplinary_records";
    /// <summary>Manage disciplinary records</summary>
    public const string ManageDisciplinaryRecords = "manage_disciplinary_records";
    /// <summary>View staff documents</summary>
    public const string ViewStaffDocuments = "view_staff_documents";
    /// <summary>Manage staff documents</summary>
    public const string ManageStaffDocuments = "manage_staff_documents";
    /// <summary>View staff position changes</summary>
    public const string ViewStaffPositionChanges = "view_staff_position_changes";
    /// <summary>Manage staff position changes</summary>
    public const string ManageStaffPositionChanges = "manage_staff_position_changes";
    /// <summary>View salary structures</summary>
    public const string ViewSalaryStructures = "view_salary_structures";
    /// <summary>Manage salary structures</summary>
    public const string ManageSalaryStructures = "manage_salary_structures";
    /// <summary>View staff complaints</summary>
    public const string ViewStaffComplaints = "view_staff_complaints";
    /// <summary>Manage staff complaints</summary>
    public const string ManageStaffComplaints = "manage_staff_complaints";
    /// <summary>View company complaints</summary>
    public const string ViewCompanyComplaints = "view_company_complaints";
    /// <summary>Manage company complaints</summary>
    public const string ManageCompanyComplaints = "manage_company_complaints";
    /// <summary>View report schedules</summary>
    public const string ViewCompanyReportSchedules = "view_company_report_schedules";
    /// <summary>Manage report schedules</summary>
    public const string ManageReportSchedules = "manage_report_schedules";
    /// <summary>View company reports</summary>
    public const string ViewCompanyReports = "view_company_reports";
    /// <summary>Manage company reports</summary>
    public const string ManageCompanyReports = "manage_company_reports";
    /// <summary>View shift templates</summary>
    public const string ViewShiftTemplates = "view_shift_templates";
    /// <summary>Manage shift templates</summary>
    public const string ManageShiftTemplates = "manage_shift_templates";
    /// <summary>View shift assignments</summary>
    public const string ViewShiftAssignments = "view_shift_assignments";
    /// <summary>Manage shift assignments</summary>
    public const string ManageShiftAssignments = "manage_shift_assignments";
    /// <summary>View shift coverage</summary>
    public const string ViewShiftCoverage = "view_shift_coverage";
    /// <summary>View company calendar</summary>
    public const string ViewCompanyCalendar = "view_company_calendar";
    /// <summary>Manage company calendar</summary>
    public const string ManageCompanyCalendar = "manage_company_calendar";
    /// <summary>Manage duty assignments</summary>
    public const string ManageDutyAssignments = "manage_duty_assignments";
    /// <summary>View leave policy</summary>
    public const string ViewLeavePolicy = "view_leave_policy";
    /// <summary>View leave requests</summary>
    public const string ViewLeaveRequests = "view_leave_requests";
    /// <summary>Manage leave requests</summary>
    public const string ManageLeaveRequests = "manage_leave_requests";
    /// <summary>View leave analytics</summary>
    public const string ViewLeaveAnalytics = "view_leave_analytics";
    /// <summary>View leave balance</summary>
    public const string ViewLeaveBalance = "view_leave_balance";
    /// <summary>Manage leave balance</summary>
    public const string ManageLeaveBalance = "manage_leave_balance";
    /// <summary>View facilities</summary>
    public const string ViewFacilities = "view_facilities";
    /// <summary>Manage facilities</summary>
    public const string ManageFacilities = "manage_facilities";
    /// <summary>View housekeeping</summary>
    public const string ViewHousekeeping = "view_housekeeping";
    /// <summary>Manage housekeeping</summary>
    public const string ManageHousekeeping = "manage_housekeeping";
    /// <summary>View work orders</summary>
    public const string ViewWorkOrders = "view_work_orders";
    /// <summary>Manage work orders</summary>
    public const string ManageWorkOrders = "manage_work_orders";
    /// <summary>View incident reports</summary>
    public const string ViewIncidentReports = "view_incident_reports";
    /// <summary>Manage incident reports</summary>
    public const string ManageIncidentReports = "manage_incident_reports";
    /// <summary>View inventory</summary>
    public const string ViewInventory = "view_inventory";
    /// <summary>Manage inventory</summary>
    public const string ManageInventory = "manage_inventory";
    /// <summary>View assets</summary>
    public const string ViewAssets = "view_assets";
    /// <summary>Manage assets</summary>
    public const string ManageAssets = "manage_assets";
    /// <summary>View financial analytics</summary>
    public const string ViewFinancialsAnalytics = "view_financials_analytics";
    /// <summary>View financial reports</summary>
    public const string ViewFinancialReports = "view_financial_reports";
    /// <summary>Manage financial reports</summary>
    public const string ManageFinancialReports = "manage_financial_reports";
    /// <summary>View company budget</summary>
    public const string ViewCompanyBudget = "view_company_budget";
    /// <summary>Manage company budgets</summary>
    public const string ManageCompanyBudgets = "manage_company_budgets";
    /// <summary>Approve monthly budgets</summary>
    public const string ApproveMonthlyBudgets = "approve_monthly_budgets";
    /// <summary>Manage budget allocations</summary>
    public const string ManageBudgetAllocations = "manage_budget_allocations";
    /// <summary>View revenue streams</summary>
    public const string ViewRevenueStreams = "view_revenue_streams";
    /// <summary>Manage revenue streams</summary>
    public const string ManageRevenueStreams = "manage_revenue_streams";
    /// <summary>View company wallet</summary>
    public const string ViewCompanyWallet = "view_company_wallet";
    /// <summary>Manage company wallets</summary>
    public const string ManageCompanyWallets = "manage_company_wallets";
    /// <summary>View wallet audit trails</summary>
    public const string ViewWalletAuditTrails = "view_wallet_audit_trails";
    /// <summary>View company transactions</summary>
    public const string ViewCompanyTransactions = "view_company_transactions";
    /// <summary>View remittances</summary>
    public const string ViewRemittances = "view_remittances";
    /// <summary>Manage remittances</summary>
    public const string ManageRemittances = "manage_remittances";
    /// <summary>View company invoices</summary>
    public const string ViewCompanyInvoices = "view_company_invoices";
    /// <summary>Manage company invoices</summary>
    public const string ManageCompanyInvoices = "manage_company_invoices";
    /// <summary>View variance reports</summary>
    public const string ViewVarianceReports = "view_variance_reports";
    /// <summary>View financial statements</summary>
    public const string ViewFinancialStatements = "view_financial_statements";
    /// <summary>View payroll</summary>
    public const string ViewPayroll = "view_payroll";
    /// <summary>Manage payroll</summary>
    public const string ManagePayroll = "manage_payroll";
    /// <summary>View payroll YTD</summary>
    public const string ViewPayrollYtd = "view_payroll_ytd";
    /// <summary>Approve payrolls</summary>
    public const string ApprovePayrolls = "approve_payrolls";
    /// <summary>Send payroll</summary>
    public const string SendPayroll = "send_payroll";
    /// <summary>Manage payroll schedules</summary>
    public const string ManagePayrollSchedules = "manage_payroll_schedules";
    /// <summary>View allocations</summary>
    public const string ViewAllocations = "view_allocations";
    /// <summary>Manage allocations</summary>
    public const string ManageAllocations = "manage_allocations";

    /// <summary>Every slug, in catalog order.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        ViewCompanyDetails,
        ManageCompanyDetails,
        ViewCompanyPlansBillings,
        ManageCompanyPlansBillings,
        ViewAllBranches,
        ManageAllBranches,
        ViewDepartments,
        ManageDepartments,
        ViewRoles,
        ManageRoles,
        ViewBranchStaff,
        ManageBranchStaff,
        ViewInvitations,
        ManageInvitations,
        ViewCompanyAuditLogs,
        ViewCompliance,
        ManageCompliance,
        ViewKitchenAnalytics,
        ViewKitchenMenu,
        ManageKitchenMenu,
        ViewKitchenBoard,
        ManageKitchenBoard,
        ViewKitchenOrders,
        ManageKitchenOrders,
        ViewReception,
        ViewReceptionAnalytics,
        ViewApprovalChain,
        ManageApprovalChain,
        ViewBookingRequests,
        ManageBooking,
        ViewRefundRequests,
        ManageRefundRequests,
        ViewGuests,
        ManageGuests,
        ViewStaffAttendance,
        ViewCompanyContracts,
        ManageCompanyContracts,
        ViewStaffPerformance,
        ManageStaffPerformance,
        ViewStaffTraining,
        ManageStaffTraining,
        ViewDisciplinaryRecords,
        ManageDisciplinaryRecords,
        ViewStaffDocuments,
        ManageStaffDocuments,
        ViewStaffPositionChanges,
        ManageStaffPositionChanges,
        ViewSalaryStructures,
        ManageSalaryStructures,
        ViewStaffComplaints,
        ManageStaffComplaints,
        ViewCompanyComplaints,
        ManageCompanyComplaints,
        ViewCompanyReportSchedules,
        ManageReportSchedules,
        ViewCompanyReports,
        ManageCompanyReports,
        ViewShiftTemplates,
        ManageShiftTemplates,
        ViewShiftAssignments,
        ManageShiftAssignments,
        ViewShiftCoverage,
        ViewCompanyCalendar,
        ManageCompanyCalendar,
        ManageDutyAssignments,
        ViewLeavePolicy,
        ViewLeaveRequests,
        ManageLeaveRequests,
        ViewLeaveAnalytics,
        ViewLeaveBalance,
        ManageLeaveBalance,
        ViewFacilities,
        ManageFacilities,
        ViewHousekeeping,
        ManageHousekeeping,
        ViewWorkOrders,
        ManageWorkOrders,
        ViewIncidentReports,
        ManageIncidentReports,
        ViewInventory,
        ManageInventory,
        ViewAssets,
        ManageAssets,
        ViewFinancialsAnalytics,
        ViewFinancialReports,
        ManageFinancialReports,
        ViewCompanyBudget,
        ManageCompanyBudgets,
        ApproveMonthlyBudgets,
        ManageBudgetAllocations,
        ViewRevenueStreams,
        ManageRevenueStreams,
        ViewCompanyWallet,
        ManageCompanyWallets,
        ViewWalletAuditTrails,
        ViewCompanyTransactions,
        ViewRemittances,
        ManageRemittances,
        ViewCompanyInvoices,
        ManageCompanyInvoices,
        ViewVarianceReports,
        ViewFinancialStatements,
        ViewPayroll,
        ManagePayroll,
        ViewPayrollYtd,
        ApprovePayrolls,
        SendPayroll,
        ManagePayrollSchedules,
        ViewAllocations,
        ManageAllocations,
    };

    private static readonly HashSet<string> Known = new(All, StringComparer.Ordinal);

    /// <summary>True when the platform recognises <paramref name="name"/> as a permission.</summary>
    public static bool IsKnown(string name) => Known.Contains(name);
}
