// <auto-generated>
//     Generated from backend/djengo-proto-helpers/src/permissions.ts.
//
//     Do not edit this file. Change the TypeScript catalog, run
//     `npm run build` in djengo-proto-helpers, then `npm run sync:dotnet`
//     to refresh every service, and commit the result.
// </auto-generated>

using System;
using System.Collections.Generic;

namespace Djengo.Shared;

/// <summary>
/// Organization permission slugs, matching the rows organization-service seeds
/// into its Permission table. A slug that is not in that table resolves to zero
/// recipients or a denied check, silently — so prefer these constants over
/// string literals anywhere a permission name crosses a service boundary.
/// </summary>
public static class Permissions
{
    // BUSINESS_USER
    /// <summary>Manage organization</summary>
    public const string ManageOrganization = "manage_organization";
    /// <summary>View settings</summary>
    public const string ViewSettings = "view_settings";
    /// <summary>Manage settings</summary>
    public const string ManageSettings = "manage_settings";
    /// <summary>View companies</summary>
    public const string ViewCompanies = "view_companies";
    /// <summary>Manage companies</summary>
    public const string ManageCompanies = "manage_companies";
    /// <summary>View branches</summary>
    public const string ViewBranches = "view_branches";
    /// <summary>Manage branches</summary>
    public const string ManageBranches = "manage_branches";
    /// <summary>Restrict branch access</summary>
    public const string RestrictBranchAccess = "restrict_branch_access";
    /// <summary>View departments</summary>
    public const string ViewDepartments = "view_departments";
    /// <summary>Manage departments</summary>
    public const string ManageDepartments = "manage_departments";
    /// <summary>View roles</summary>
    public const string ViewRoles = "view_roles";
    /// <summary>Manage roles</summary>
    public const string ManageRoles = "manage_roles";
    /// <summary>View partners</summary>
    public const string ViewPartners = "view_partners";
    /// <summary>Manage partners</summary>
    public const string ManagePartners = "manage_partners";
    /// <summary>View staff</summary>
    public const string ViewStaff = "view_staff";
    /// <summary>Manage staff</summary>
    public const string ManageStaff = "manage_staff";
    /// <summary>Manage invitations</summary>
    public const string ManageInvitations = "manage_invitations";
    /// <summary>View audit</summary>
    public const string ViewAudit = "view_audit";
    /// <summary>Manage audit</summary>
    public const string ManageAudit = "manage_audit";

    // DEPARTMENT
    /// <summary>Access kitchen</summary>
    public const string AccessKitchen = "access_kitchen";
    /// <summary>Manage kitchen</summary>
    public const string ManageKitchen = "manage_kitchen";
    /// <summary>Access reception</summary>
    public const string AccessReception = "access_reception";
    /// <summary>Manage reception</summary>
    public const string ManageReception = "manage_reception";
    /// <summary>Access hotel</summary>
    public const string AccessHotel = "access_hotel";
    /// <summary>Manage hotel</summary>
    public const string ManageHotel = "manage_hotel";
    /// <summary>Access restaurant</summary>
    public const string AccessRestaurant = "access_restaurant";
    /// <summary>Manage restaurant</summary>
    public const string ManageRestaurant = "manage_restaurant";

    // STAFF
    /// <summary>View dashboard</summary>
    public const string ViewDashboard = "view_dashboard";
    /// <summary>View profile</summary>
    public const string ViewProfile = "view_profile";
    /// <summary>Manage profile</summary>
    public const string ManageProfile = "manage_profile";
    /// <summary>Access branch</summary>
    public const string AccessBranch = "access_branch";
    /// <summary>Manage branch</summary>
    public const string ManageBranch = "manage_branch";
    /// <summary>View all branches</summary>
    public const string ViewAllBranches = "view_all_branches";
    /// <summary>View branch staff</summary>
    public const string ViewBranchStaff = "view_branch_staff";
    /// <summary>View branch leave</summary>
    public const string ViewBranchLeave = "view_branch_leave";
    /// <summary>View branch approvals</summary>
    public const string ViewBranchApprovals = "view_branch_approvals";
    /// <summary>View branch financials</summary>
    public const string ViewBranchFinancials = "view_branch_financials";
    /// <summary>View branch shifts</summary>
    public const string ViewBranchShifts = "view_branch_shifts";
    /// <summary>View branch tasks</summary>
    public const string ViewBranchTasks = "view_branch_tasks";
    /// <summary>View branch reception</summary>
    public const string ViewBranchReception = "view_branch_reception";
    /// <summary>View branch facility</summary>
    public const string ViewBranchFacility = "view_branch_facility";
    /// <summary>Access facility</summary>
    public const string AccessFacility = "access_facility";
    /// <summary>Manage facility</summary>
    public const string ManageFacility = "manage_facility";
    /// <summary>View operations</summary>
    public const string ViewOperations = "view_operations";
    /// <summary>Manage operations</summary>
    public const string ManageOperations = "manage_operations";
    /// <summary>View tasks</summary>
    public const string ViewTasks = "view_tasks";
    /// <summary>Manage tasks</summary>
    public const string ManageTasks = "manage_tasks";
    /// <summary>View inventory</summary>
    public const string ViewInventory = "view_inventory";
    /// <summary>Manage inventory</summary>
    public const string ManageInventory = "manage_inventory";
    /// <summary>View assets</summary>
    public const string ViewAssets = "view_assets";
    /// <summary>Manage assets</summary>
    public const string ManageAssets = "manage_assets";
    /// <summary>View reservations</summary>
    public const string ViewReservations = "view_reservations";
    /// <summary>Manage reservations</summary>
    public const string ManageReservations = "manage_reservations";
    /// <summary>Approve reservations</summary>
    public const string ApproveReservations = "approve_reservations";
    /// <summary>View guests</summary>
    public const string ViewGuests = "view_guests";
    /// <summary>Manage guests</summary>
    public const string ManageGuests = "manage_guests";
    /// <summary>View schedule</summary>
    public const string ViewSchedule = "view_schedule";
    /// <summary>Manage schedule</summary>
    public const string ManageSchedule = "manage_schedule";
    /// <summary>View shifts</summary>
    public const string ViewShifts = "view_shifts";
    /// <summary>Manage shifts</summary>
    public const string ManageShifts = "manage_shifts";
    /// <summary>View time</summary>
    public const string ViewTime = "view_time";
    /// <summary>Manage time</summary>
    public const string ManageTime = "manage_time";
    /// <summary>View attendance</summary>
    public const string ViewAttendance = "view_attendance";
    /// <summary>Manage attendance</summary>
    public const string ManageAttendance = "manage_attendance";
    /// <summary>View leave</summary>
    public const string ViewLeave = "view_leave";
    /// <summary>Manage leave</summary>
    public const string ManageLeave = "manage_leave";
    /// <summary>Approve leave</summary>
    public const string ApproveLeave = "approve_leave";
    /// <summary>View leave policy</summary>
    public const string ViewLeavePolicy = "view_leave_policy";
    /// <summary>Manage leave policy</summary>
    public const string ManageLeavePolicy = "manage_leave_policy";
    /// <summary>View calendar</summary>
    public const string ViewCalendarEvents = "view_calendar_events";
    /// <summary>Manage calendar</summary>
    public const string ManageCalendarEvents = "manage_calendar_events";
    /// <summary>View approvals</summary>
    public const string ViewApprovals = "view_approvals";
    /// <summary>Manage approvals</summary>
    public const string ManageApprovals = "manage_approvals";
    /// <summary>Manage approval chains</summary>
    public const string ManageApprovalChains = "manage_approval_chains";
    /// <summary>View communication</summary>
    public const string ViewCommunication = "view_communication";
    /// <summary>Manage communication</summary>
    public const string ManageCommunication = "manage_communication";
    /// <summary>View complaints</summary>
    public const string ViewComplaints = "view_complaints";
    /// <summary>Manage complaints</summary>
    public const string ManageComplaints = "manage_complaints";
    /// <summary>View staff profiles</summary>
    public const string ViewStaffProfiles = "view_staff_profiles";
    /// <summary>Manage staff profiles</summary>
    public const string ManageStaffProfiles = "manage_staff_profiles";
    /// <summary>View HR records</summary>
    public const string ViewHrRecords = "view_hr_records";
    /// <summary>Manage HR records</summary>
    public const string ManageHrRecords = "manage_hr_records";
    /// <summary>View finances</summary>
    public const string ViewFinances = "view_finances";
    /// <summary>Manage finances</summary>
    public const string ManageFinances = "manage_finances";
    /// <summary>View invoices</summary>
    public const string ViewInvoices = "view_invoices";
    /// <summary>Manage invoices</summary>
    public const string ManageInvoices = "manage_invoices";
    /// <summary>Manage billing policy</summary>
    public const string ManageBillingPolicy = "manage_billing_policy";
    /// <summary>View procurement</summary>
    public const string ViewProcurement = "view_procurement";
    /// <summary>Manage procurement</summary>
    public const string ManageProcurement = "manage_procurement";
    /// <summary>Approve procurement</summary>
    public const string ApproveProcurement = "approve_procurement";
    /// <summary>View payrolls</summary>
    public const string ViewPayrolls = "view_payrolls";
    /// <summary>Manage payrolls</summary>
    public const string ManagePayrolls = "manage_payrolls";
    /// <summary>Approve payrolls</summary>
    public const string ApprovePayrolls = "approve_payrolls";
    /// <summary>Send payroll</summary>
    public const string SendPayroll = "send_payroll";
    /// <summary>View payroll reports</summary>
    public const string ViewPayrollReports = "view_payroll_reports";
    /// <summary>Manage payroll schedules</summary>
    public const string ManagePayrollSchedules = "manage_payroll_schedules";
    /// <summary>View monthly budgets</summary>
    public const string ViewMonthlyBudgets = "view_monthly_budgets";
    /// <summary>Manage monthly budgets</summary>
    public const string ManageMonthlyBudgets = "manage_monthly_budgets";
    /// <summary>Approve monthly budgets</summary>
    public const string ApproveMonthlyBudgets = "approve_monthly_budgets";
    /// <summary>View branch budget</summary>
    public const string ViewBranchBudget = "view_branch_budget";
    /// <summary>View branch allocations</summary>
    public const string ViewBranchAllocations = "view_branch_allocations";
    /// <summary>Manage branch allocations</summary>
    public const string ManageBranchAllocations = "manage_branch_allocations";
    /// <summary>Approve branch allocations</summary>
    public const string ApproveBranchAllocations = "approve_branch_allocations";
    /// <summary>View allocations</summary>
    public const string ViewAllocations = "view_allocations";
    /// <summary>Manage allocations</summary>
    public const string ManageAllocations = "manage_allocations";
    /// <summary>Request funds</summary>
    public const string RequestFunds = "request_funds";
    /// <summary>View fund requests</summary>
    public const string ViewFundRequests = "view_fund_requests";
    /// <summary>Approve fund requests</summary>
    public const string ApproveFundRequests = "approve_fund_requests";
    /// <summary>Request extra funds</summary>
    public const string RequestExtraFunds = "request_extra_funds";
    /// <summary>View extra fund requests</summary>
    public const string ViewExtraFundRequests = "view_extra_fund_requests";
    /// <summary>Approve extra fund requests</summary>
    public const string ApproveExtraFundRequests = "approve_extra_fund_requests";
    /// <summary>View disbursements</summary>
    public const string ViewDisbursements = "view_disbursements";
    /// <summary>Manage disbursements</summary>
    public const string ManageDisbursements = "manage_disbursements";
    /// <summary>Approve disbursements</summary>
    public const string ApproveDisbursements = "approve_disbursements";

    /// <summary>Every slug, in catalog order.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        ManageOrganization,
        ViewSettings,
        ManageSettings,
        ViewCompanies,
        ManageCompanies,
        ViewBranches,
        ManageBranches,
        RestrictBranchAccess,
        ViewDepartments,
        ManageDepartments,
        ViewRoles,
        ManageRoles,
        ViewPartners,
        ManagePartners,
        ViewStaff,
        ManageStaff,
        ManageInvitations,
        ViewAudit,
        ManageAudit,
        AccessKitchen,
        ManageKitchen,
        AccessReception,
        ManageReception,
        AccessHotel,
        ManageHotel,
        AccessRestaurant,
        ManageRestaurant,
        ViewDashboard,
        ViewProfile,
        ManageProfile,
        AccessBranch,
        ManageBranch,
        ViewAllBranches,
        ViewBranchStaff,
        ViewBranchLeave,
        ViewBranchApprovals,
        ViewBranchFinancials,
        ViewBranchShifts,
        ViewBranchTasks,
        ViewBranchReception,
        ViewBranchFacility,
        AccessFacility,
        ManageFacility,
        ViewOperations,
        ManageOperations,
        ViewTasks,
        ManageTasks,
        ViewInventory,
        ManageInventory,
        ViewAssets,
        ManageAssets,
        ViewReservations,
        ManageReservations,
        ApproveReservations,
        ViewGuests,
        ManageGuests,
        ViewSchedule,
        ManageSchedule,
        ViewShifts,
        ManageShifts,
        ViewTime,
        ManageTime,
        ViewAttendance,
        ManageAttendance,
        ViewLeave,
        ManageLeave,
        ApproveLeave,
        ViewLeavePolicy,
        ManageLeavePolicy,
        ViewCalendarEvents,
        ManageCalendarEvents,
        ViewApprovals,
        ManageApprovals,
        ManageApprovalChains,
        ViewCommunication,
        ManageCommunication,
        ViewComplaints,
        ManageComplaints,
        ViewStaffProfiles,
        ManageStaffProfiles,
        ViewHrRecords,
        ManageHrRecords,
        ViewFinances,
        ManageFinances,
        ViewInvoices,
        ManageInvoices,
        ManageBillingPolicy,
        ViewProcurement,
        ManageProcurement,
        ApproveProcurement,
        ViewPayrolls,
        ManagePayrolls,
        ApprovePayrolls,
        SendPayroll,
        ViewPayrollReports,
        ManagePayrollSchedules,
        ViewMonthlyBudgets,
        ManageMonthlyBudgets,
        ApproveMonthlyBudgets,
        ViewBranchBudget,
        ViewBranchAllocations,
        ManageBranchAllocations,
        ApproveBranchAllocations,
        ViewAllocations,
        ManageAllocations,
        RequestFunds,
        ViewFundRequests,
        ApproveFundRequests,
        RequestExtraFunds,
        ViewExtraFundRequests,
        ApproveExtraFundRequests,
        ViewDisbursements,
        ManageDisbursements,
        ApproveDisbursements,
    };

    private static readonly HashSet<string> Known = new(All, StringComparer.Ordinal);

    /// <summary>True when the platform recognises <paramref name="name"/> as a permission.</summary>
    public static bool IsKnown(string name) => Known.Contains(name);
}
